version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: rubika_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: rubika_osint
    ports:
      - "5433:5432" # تغییر پورت هاست به 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: rubika_cache
    restart: always
    ports:
      - "6380:6379"

volumes:
  postgres_data: